module.exports = {
  apps: [
    {
      name: "chatcore-web",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: 1,
      exec_mode: "cluster",
      watch: false,
      ignore_watch: ["node_modules", ".git", "logs"],
      max_memory_restart: "500M",
      log_file: "logs/combined.log",
      out_file: "logs/out.log",
      error_file: "logs/error.log",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      max_restarts: 10,
      min_uptime: "10s",
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        PINECONE_API_KEY: process.env.PINECONE_API_KEY,
        PINECONE_ENVIRONMENT: process.env.PINECONE_ENVIRONMENT,
        PINECONE_INDEX_NAME: process.env.PINECONE_INDEX_NAME,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_BUCKET_REGION: process.env.AWS_BUCKET_REGION,
        BUCKET_NAME: process.env.BUCKET_NAME,
        AWS_SDK_LOAD_CONFIG: process.env.AWS_SDK_LOAD_CONFIG,
        DATABASE_URL: process.env.DATABASE_URL,
        DIRECT_URL: process.env.DIRECT_URL,
        LLAMA_CLOUD_API_KEY: process.env.LLAMA_CLOUD_API_KEY,
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
        NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
        NEXTAUTH_URL: process.env.NEXTAUTH_URL,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        STRIPE_MONTHLY_PRICE_ID: process.env.STRIPE_MONTHLY_PRICE_ID,
        STRIPE_YEARLY_PRICE_ID: process.env.STRIPE_YEARLY_PRICE_ID,
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
          process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
        TAVILY_API_KEY: process.env.TAVILY_API_KEY,
      },
    },
    {
      name: "chatcore-cron",
      script: "npm",
      args: "run cron:run",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "200M",
      log_file: "logs/cron-combined.log",
      out_file: "logs/cron-out.log",
      error_file: "logs/cron-error.log",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      env_production: {
        NODE_ENV: "production",
        DATABASE_URL: process.env.DATABASE_URL,
        DIRECT_URL: process.env.DIRECT_URL,
      },
    },
  ],
};
