module.exports = {
  apps: [
    {
      name: "chatcore-web",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: 1,
      exec_mode: "cluster",
      watch: false,
      ignore_watch: ["node_modules", ".git", "logs"],
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        PINECONE_API_KEY: process.env.PINECONE_API_KEY,
        PINECONE_ENVIRONMENT: process.env.PINECONE_ENVIRONMENT,
        PINECONE_INDEX_NAME: process.env.PINECONE_INDEX_NAME,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_BUCKET_REGION: process.env.AWS_BUCKET_REGION,
        BUCKET_NAME: process.env.BUCKET_NAME,
        AWS_SDK_LOAD_CONFIG: process.env.AWS_SDK_LOAD_CONFIG,
        DATABASE_URL: process.env.DATABASE_URL,
        DIRECT_URL: process.env.DIRECT_URL,
        LLAMA_CLOUD_API_KEY: process.env.LLAMA_CLOUD_API_KEY,
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
        NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
        NEXTAUTH_URL: process.env.NEXTAUTH_URL,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
      },
    },
    {
      name: "chatcore-cron",
      script: "npm",
      args: "run start:cron",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      env_production: {
        NODE_ENV: "production",
        DATABASE_URL: process.env.DATABASE_URL,
        DIRECT_URL: process.env.DIRECT_URL,
      },
    },
  ],
};
